#===========================================================
#     _____     _                    _                     #
#    |_   _|   | |                  (_)                    #
#      | | __ _| |__   ___ _ __  ___ _  ___  _ __  ___     #
#      | |/ _` | '_ \ / _ \ '_ \/ __| |/ _ \| '_ \/ __|    #
#      | | (_| | |_) |  __/ | | \__ \ | (_) | | | \__ \    #
#      \_/\__,_|_.__/ \___|_| |_|___/_|\___/|_| |_|___/    #
#                                                          #
#===========================================================

# Char used for represent dimensions in placeholder
dimensionChar: "●"

# Minecraft colors for placeholder char
colors:
    NORMAL: "&a"
    NETHER: "&4"
    THE_END: "&5"
    CUSTOM: "&7"

# Ignored worlds where placeholder is won't show
# Case-sensitive
ignoredWorlds:
    - ExampleWorld
