#===========================================================
#     _____     _                    _                     #
#    |_   _|   | |                  (_)                    #
#      | | __ _| |__   ___ _ __  ___ _  ___  _ __  ___     #
#      | |/ _` | '_ \ / _ \ '_ \/ __| |/ _ \| '_ \/ __|    #
#      | | (_| | |_) |  __/ | | \__ \ | (_) | | | \__ \    #
#      \_/\__,_|_.__/ \___|_| |_|___/_|\___/|_| |_|___/    #
#                                                          #
#===========================================================

# Char used for represent dimensions in placeholder
dimensionChar: "●"

# Colors for placeholder char
# Allowed minecraft colors: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
# Not case-sensitive
colors:
    normal: "GREEN"
    nether: "DARK_RED"
    end: "DARK_PURPLE"
    custom: "GRAY"

# Ignored worlds
# Case-sensitive
ignoredWorlds:
    - ExampleWorld
